# Generated by Django 3.0.1 on 2020-01-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statics',
        ),
    ]
